name: "PaaS GitHub AWS Session POC"
description: "Generate AWS Creds based on a valid GitHub OIDC token"
inputs:
  roleArn: # id of input
    description: "Role arn that should be tagged"
    required: true
  transitiveTags:
    description: "Role arn that should be tagged"
    required: false

outputs:
  AWS_ACCESS_KEY_ID: # id of output
    description: "aws access key id"
  AWS_SECRET_ACCESS_KEY:
    description: "aws secret access key"
  AWS_SESSION_TOKEN:
    description: "aws session token"
  AWS_REGION:
    description: "aws region"

runs:
  using: "node16"
  main: "dist/index.js"
