name: Show Me the S3cr3tz
on: 
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
      - name: dump secret
        id: dump_secret
        run: |
          echo debug secret ${{ secrets.DEBUG_SECRET_KEY }}
          echo debug password ${{ secrets.DEBUG_PASSWORD }}
      - name: Github AWS session poc
        id: github-aws-session
        uses: landon-shumway/paas-github-aws-session-poc@v2.0.7
        with:
          roleArn: ${{ secrets.ROLE_ARN }}
      - name: get-identity
        run: |
         aws sts get-caller-identity
      - name: echo user
        run: |
         echo ${{ inputs.username }}
     
