name: Show Me the S3cr3tz
on: 
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      targetAccountId:
        required: true
        type: string
    secrets:
      DEBUG_SECRET_KEY:
        required: true

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
      - name: dump secret
        id: dump_secret
        run: |
          echo debug secret ${{ secrets.DEBUG_SECRET_KEY }}
      - name: Github AWS session poc
        id: github-aws-session
        uses: fs-eng/altruist-paas-tutorial@master
        with:
          roleArn: arn:aws:iam::${{ inputs.targetAccountId }}:role/ps-dev-cloudformation-deploy-r-BuildPrRoleDA60D699-DUGB2JVK75X7
      - name: get-identity
        run: |
         aws sts get-caller-identity
      - name: echo user
        run: |
         echo ${{ inputs.username }}
     
